### ISSUE TITLE
Audio chips aren't visible

### ISSUE THREAD

**Issue by Kaccana-Bhikkhu** [Kaccana-Bhikkhu/qs-archive#19]
I pulled the audio-player branch and ran the QSarchive.py to update all html files. However, I can't see the audio chip player. Here's what it looks like on mom's Mac:

<img width="636" alt="Screen Shot 2023-06-28 at 11 01 35 AM" src="https://github.com/Kaccana-Bhikkhu/qs-archive/assets/121373455/5783f9db-92c8-40e8-b5da-2af91abdf234">

I pushed the updated html files back to audio-player, but I'm not up to debugging web Javascript. Could you take a look at this when you get the chance? Thanks much.

**Comment by mageowl** [comment]
This is now fixed, I belive.
