### ISSUE TITLE
The progress bar displays incorrectly after clicking the play button before the player fully loads.

### ISSUE THREAD

**Issue by Kaccana-Bhikkhu** [Kaccana-Bhikkhu/qs-archive#27]
[Same as Pull Request 20 Issue 8](https://github.com/Kaccana-Bhikkhu/qs-archive/pull/20#issuecomment-1640427386)
To reproduce:

Load the [2013 Thanksgiving Retreat](https://kaccana-bhikkhu.github.io/qs-archive/pages/index.html#events/TG2013.html) and quickly scroll down to the bottom and click on Session 8, Excerpt 19, which is 7 minutes, 6 seconds long. The player at first shows:

image

5 - 10 seconds later, the audio loads and begins to play. The audio plays for 7:06, but the progress bar completes at 1:40:

image

This problem may be easier to reproduce using the 1,000+ item All Excerpts page.

Also, I wonder if the player could say something like "Loading..." instead of "0:00 / Nan:Nan"?

I'm happy to merge the pull request without this fix if it turns out to be too difficult.

**Comment by mageowl** [comment]
This is now fixed on my end.
