### ISSUE TITLE
Improve look of download link

### ISSUE THREAD

**Issue by Kaccana-Bhikkhu** [Kaccana-Bhikkhu/qs-archive#36]
Your solution to display the Download Audio link below the time is OK for functionality, but I had in mind something that would mesh better with the other page styling. I had thought to use a download icon either to the left or right of the play button as shown below.

![image](https://github.com/Kaccana-Bhikkhu/qs-archive/assets/121373455/ee56c9fc-9680-42ba-9281-c4f95c85968a)

or

![image](https://github.com/Kaccana-Bhikkhu/qs-archive/assets/121373455/8540ebb3-a14a-47e4-a4b9-4c0edb4c67cb)

The button styles should match; I'm guessing you have a .svg editor that can do this. I have a slight preference for the second layout, but we can code whatever is simpler.

I suspect this might require a coordinated effort modifying Prototype.py as well as the various .js and .css files. I have created a new player-fixes-2 branch for us to fix this on.

Also, can we use the download attribute of `<a href>` so the mp3 file downloads immediately (like on [abhayagiri.org/talks](https://abhayagiri.org/talks))? Currently clicking the download link switches to a full-page mp3 player on my computer (Windows Chrome).

**Comment by mageowl** [comment]
As for the attribute, for some reason the browser disregards it on the download link. I tried it before, but it might just be my end.
