### ISSUE TITLE
Going back sometimes jumps to unexpected location

### ISSUE THREAD

**Issue by Kaccana-Bhikkhu** [Kaccana-Bhikkhu/qs-archive#52]
After following certain links, and then pressing the back button, one ends up at an unexpected scroll position.

To reproduce:
1. Go to https://kaccana-bhikkhu.github.io/qs-archive/pages/index.html#events/Metta2008.html#Metta2008_S03. The scroll position is now at Session 3 of the Metta Retreat. (Going to https://www.abhayagiri.org/media/discs/questions/pages/index.html#events/Metta2008.html and scrolling down to Session 3 produces the same effect.)
2. Click on the tag [Lay teachers].
3. Now press the back button. The scroll position is now in the middle of Session 1.

I'm puzzled because clicking on either [Lay life] or [Monastic life] doesn't cause this issue.

I thought the problem could be caused by the location of this tag relative to the text `//`: [[Lay teachers](https://kaccana-bhikkhu.github.io/qs-archive/pages/index.html#tags/lay-teachers.html)] // [[Monastic life](https://kaccana-bhikkhu.github.io/qs-archive/pages/index.html#tags/monastic-life.html)]. However, changing this text to `||` doesn't solve the problem.

The console sometimes reports the error:

![image](https://github.com/Kaccana-Bhikkhu/qs-archive/assets/121373455/f9c7c703-7f37-419f-aa40-b4321d16faa2)

when following this procedure, but the error seems to happen for any tag. The error is suppressed when running the page on Live Server. (I notice that no matter how many `../` one concatenates at the beginning of a path, Live Server goes no deeper than its root directory and does not report an error.)

**Comment by mageowl** [comment]
This is impossible to fix. The way that the browser handles the scrolling with back button is not changeable without some serious workarounds (re-implementing the entire scrolling system) and would cause it to break on many browsers.
